<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Desa_model extends CI_Model
{

    public $table = 'desa';
    public $id = 'id_desa';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function get_desa_spesifik()
    {
        $this->db->select('*');
        $this->db->from('desa');
        $this->db->join('kecamatan', 'desa.id_kecamatan_fk = kecamatan.id_kecamatan');
        $query = $this->db->get();
        return $query->result();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_desa', $q);
	$this->db->or_like('id_kecamatan_fk', $q);
	$this->db->or_like('nama_desa', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_desa', $q);
	$this->db->or_like('id_kecamatan_fk', $q);
	$this->db->or_like('nama_desa', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Desa_model.php */
/* Location: ./application/models/Desa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-09-04 16:50:50 */
/* http://harviacode.com */