<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kota_model extends CI_Model
{

    public $table = 'kota';
    public $id = 'id_kota';
    public $order = 'DESC';
    public $kd = 'id_provinsi_fk';

    function __construct()
    {
        parent::__construct();
    }

    function get_kota_spesifik()
    {
        $this->db->select('*');
        $this->db->from('kota');
        $this->db->join('provinsi', 'kota.id_provinsi_fk = provinsi.id_provinsi','inner');
        $this->db->order_by('nama_kota');
        $query = $this->db->get();
        return $query->result();
        // $this->db->where($this->kd, $kd);
        // return $this->db->get($this->table)->result();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_kota', $q);
	$this->db->or_like('id_provinsi_fk', $q);
	$this->db->or_like('nama_kota', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_kota', $q);
	$this->db->or_like('id_provinsi_fk', $q);
	$this->db->or_like('nama_kota', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Kota_model.php */
/* Location: ./application/models/Kota_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-09-04 16:43:40 */
/* http://harviacode.com */