<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sub_menu_model extends CI_Model
{

    public $table = 'sub_menu';
    public $men = 'menu';
    public $id = 'id';
    public $kd_m = 'kode_menu';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('kode_menu', $q);
	$this->db->or_like('title', $q);
	$this->db->or_like('url', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('kode_menu', $q);
	$this->db->or_like('title', $q);
	$this->db->or_like('url', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function join_datak($x)
    {
        $this->db->where($this->kd_m, $x);
        return $this->db->get($this->men)->row();
    }

}

/* End of file Sub_menu_model.php */
/* Location: ./application/models/Sub_menu_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-05-24 15:22:20 */
/* http://harviacode.com */