<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Survey_model extends CI_Model
{

    public $table = 'survey';
    public $id = 'kd_surv';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('*');
        $this->db->from('survey');
        $this->db->join('penduduk', 'survey.no_kk = penduduk.no_kk','inner');
        $query = $this->db->get();
        return $query->result();
        // $this->db->order_by($this->id, $this->order);
        // return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('kd_surv', $q);
	$this->db->or_like('no_kk', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('kondisi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('kd_surv', $q);
	$this->db->or_like('survey.no_kk', $q);
	$this->db->or_like('survey.nik', $q);
	$this->db->or_like('survey.nama', $q);
	$this->db->or_like('kondisi', $q);
	// $this->db->limit($limit, $start);
 //        return $this->db->get($this->table)->result();
        $this->db->select('*');
        $this->db->from('survey');
        $this->db->join('penduduk', 'survey.no_kk = penduduk.no_kk','inner');
        $this->db->limit($limit, $start);
        $query = $this->db->get();
        return $query->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Survey_model.php */
/* Location: ./application/models/Survey_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-21 07:25:33 */
/* http://harviacode.com */